id: I8D4A085D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T21:51:36+00:00'
last_modified: '2022-06-07T21:22:24.577493+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W24766
  title: གཡག་ཊཱིཀ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '4351':
      image_group_id: I1KG5542
      title: ''
      total_pages: 808
      order: 1
      base_file: 4351.txt
    0F64:
      image_group_id: I1KG5543
      title: ''
      total_pages: 704
      order: 2
      base_file: 0F64.txt
    86BA:
      image_group_id: I1KG5544
      title: ''
      total_pages: 664
      order: 3
      base_file: 86BA.txt
    D234:
      image_group_id: I1KG5545
      title: ''
      total_pages: 702
      order: 4
      base_file: D234.txt
    1D44:
      image_group_id: I1KG5546
      title: ''
      total_pages: 786
      order: 5
      base_file: 1D44.txt
    B9CC:
      image_group_id: I1KG5547
      title: ''
      total_pages: 958
      order: 6
      base_file: B9CC.txt
    FFEF:
      image_group_id: I1KG5548
      title: ''
      total_pages: 808
      order: 7
      base_file: FFEF.txt
    '5842':
      image_group_id: I1KG5549
      title: ''
      total_pages: 688
      order: 8
      base_file: 5842.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
