id: I8D4A085D
legacy_id: P004245
ocr_import_info:
  bdrc_scan_id: W24766
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T21:48:33'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:30:32.620817+00:00'
last_modified: 2022-09-02 13:37:53.612968
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W24766
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW24766
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཡག་ཊཱིཀ
  author: གཡག་སྟོན་སངས་རྒྱས་དཔལ།
statistics:
  ocr_word_mean_confidence_index: 0.536995397804003
  ocr_word_median_confidence_index: 0.5299999713897705
quality: null
bases:
  I1KG5544:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5544
      total_pages: 664
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG5544.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5571571389947817
    legacy_id: v003
  I1KG5543:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5543
      total_pages: 704
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG5543.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5259443675509916
    legacy_id: v002
  I1KG5548:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5548
      total_pages: 808
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG5548.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5246102150172288
    legacy_id: v007
  I1KG5547:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5547
      total_pages: 958
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG5547.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5258055926233293
    legacy_id: v006
  I1KG5549:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5549
      total_pages: 688
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG5549.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5285082483402481
    legacy_id: v008
  I1KG5542:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5542
      total_pages: 808
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5542.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6174830849731153
    legacy_id: v001
  I1KG5545:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5545
      total_pages: 702
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG5545.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5271145582285564
    legacy_id: v004
  I1KG5546:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5546
      total_pages: 786
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG5546.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5285746917579267
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
