id: P004245
initial_creation_type: ocr
source_metadata:
  id: bdr:W24766
  title: གཡག་ཊཱིཀ།
  author: ''
  volumes:
    cc239263701f460cb094e5c3ae8106da:
      image_group_id: I1KG5542
      title: ''
      volume_number: 1
      total_pages: 808
    779c478a36824f4184aba29cee01d31d:
      image_group_id: I1KG5543
      title: ''
      volume_number: 2
      total_pages: 704
    69b73e481eeb4dcebe194513f200c833:
      image_group_id: I1KG5544
      title: ''
      volume_number: 3
      total_pages: 664
    275eaabf77db469fbf9f98aa622f6e60:
      image_group_id: I1KG5545
      title: ''
      volume_number: 4
      total_pages: 702
    201210a5f88247bcb05676b492397d7f:
      image_group_id: I1KG5546
      title: ''
      volume_number: 5
      total_pages: 786
    35347dee129e419dba4932800341563a:
      image_group_id: I1KG5547
      title: ''
      volume_number: 6
      total_pages: 958
    90498e4ab70c441fa03301d3ca20f22b:
      image_group_id: I1KG5548
      title: ''
      volume_number: 7
      total_pages: 808
    decc2d7b809e4c26b41a59c650919f2f:
      image_group_id: I1KG5549
      title: ''
      volume_number: 8
      total_pages: 688
